### ISSUE TITLE
inline template:163:90 caused by: DISQUS is not

### ISSUE THREAD

**Issue by OdaiTu** [JayChase/angular2-disqus#9]
i just did the same steps and i got this error 

inline template:163:90 caused by: DISQUS is not

angular v : 2.4.10

**Comment by JayChase** [comment]
Hi can you let me have more details or share your repository with me so I can take a look?

**Comment by OdaiTu** [comment]
ok

im using it like this

`<disqus-thread [page-identifier]="selectednews.id" [page-url]="'https://www.live.al-aalem.com/news/'+ selectednews.id+'-'+selectednews.seo_name"></disqus-thread>`

and the error in my console is like this

![image](https://user-images.githubusercontent.com/12837840/28354603-35a2e3b2-6c69-11e7-9dd1-ef1815db481c.png)

![image](https://user-images.githubusercontent.com/12837840/28354631-50eba64a-6c69-11e7-999d-97291c0f3ccf.png)


![image](https://user-images.githubusercontent.com/12837840/28354655-66d4d198-6c69-11e7-81c9-3201aabd3d54.png)

**Comment by JayChase** [comment]
Have you got the disqus script in the body section https://github.com/JayChase/angular2-disqus#add-the-disqus-script ? It looks like that might be the problem.

**Comment by OdaiTu** [comment]
@JayChase  yes thank you but i wonder why this show

![image](https://user-images.githubusercontent.com/12837840/28489202-9e3824f6-6ec5-11e7-8944-61845d3d9518.png)


i want just the comments block not the block below 
and can i choose a arabic language ?

**Comment by JayChase** [comment]
There is a page-language property you can set which should work. The details should be on the disqus site somewhere. To just show the comments go to the admin page on their site and under **Configure Disqus for Your Site** there will be a setting **Discovery**. Uncheck this and that should get rid of everything but the comments. Hope this helps. I'll close this issue off for now.

**Comment by OdaiTu** [comment]
thank u
@JayChase  i added the [page-language]="Arabic" like this and once Ar like this
but no thing changed
for the section below i dont understand u how to make i hidden ?
im using this repo to dealing with disquse in my angular app and there site dont dealing with angular 2
im right ?

**Comment by OdaiTu** [comment]
@JayChase  :)

**Comment by JayChase** [comment]
Hi. I did a plunk for you [here](http://embed.plnkr.co/i8aYxo/). It is working with [page-language]="''ar'" with the single quotes.

**Comment by OdaiTu** [comment]
@JayChase  thank you very much you saved my life
its now this section i have visit the site of disqus but i cant or intergrate the site with my app since is no spasific code to put it in my app
 how to remove it

![image](https://user-images.githubusercontent.com/12837840/29164752-3c4ee96a-7dc9-11e7-9cc9-a886cf778ac8.png)
